main: com.tj6200.autocraft.AutoCraft
name: AutoCraftingPlugin
version: 1.2
api-version: 1.17
author: tj6200
commands:
  reloadrecipes:
    description: "Reloads recipes for the Autocrafters"
    usage: /reloadrecipes
    permission: op